using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Discourse.Core;
using Discourse.Core.ErrorResponse;
using Discourse.Core.Exceptions;
using Discourse.Core.Models;
using Discourse.Core.Request;
using Discourse.Core.Response;
using Discourse.Models;
using Discourse.Models.Enums;

namespace Discourse.Api;

public sealed class Uploads
{
    private readonly RawClient _rawClient;
    private readonly Server _server;

    internal Uploads(RawClient rawClient, Server server)
    {
        _rawClient = rawClient;
        _server = server;
    }

    /// <summary>
    /// Abort multipart upload
    /// </summary>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsAbortMultipartJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// This endpoint aborts the multipart upload initiated with /create-multipart.
    /// This should be used when cancelling the upload. It does not matter if parts
    /// were already uploaded into the external storage provider.
    /// <para>
    /// You must have the correct permissions and CORS settings configured in your
    /// external provider. We support AWS S3 as the default. See:
    /// </para>
    /// <para>
    /// https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
    /// </para>
    /// <para>
    /// An external file store must be set up and <c>enable_direct_s3_uploads</c> must
    /// be set to true for this endpoint to function.
    /// </para>
    /// </remarks>
    public Task<UploadsAbortMultipartJsonResponse> AbortMultipart(UploadsAbortMultipartJsonRequest? body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads/abort-multipart.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<UploadsAbortMultipartJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Generates batches of presigned URLs for multipart parts
    /// </summary>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsBatchPresignMultipartPartsJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Multipart uploads are uploaded in chunks or parts to individual presigned
    /// URLs, similar to the one generated by /generate-presigned-put. The part
    /// numbers provided must be between 1 and 10000. The total number of parts
    /// will depend on the chunk size in bytes that you intend to use to upload
    /// each chunk. For example a 12MB file may have 2 5MB chunks and a final
    /// 2MB chunk, for part numbers 1, 2, and 3.
    /// <para>
    /// This endpoint will return a presigned URL for each part number provided,
    /// which you can then use to send PUT requests for the binary chunk corresponding
    /// to that part. When the part is uploaded, the provider should return an
    /// ETag for the part, and this should be stored along with the part number,
    /// because this is needed to complete the multipart upload.
    /// </para>
    /// <para>
    /// You must have the correct permissions and CORS settings configured in your
    /// external provider. We support AWS S3 as the default. See:
    /// </para>
    /// <para>
    /// https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
    /// </para>
    /// <para>
    /// An external file store must be set up and <c>enable_direct_s3_uploads</c> must
    /// be set to true for this endpoint to function.
    /// </para>
    /// </remarks>
    public Task<UploadsBatchPresignMultipartPartsJsonResponse> BatchPresignMultipartParts(UploadsBatchPresignMultipartPartsJsonRequest? body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads/batch-presign-multipart-parts.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<UploadsBatchPresignMultipartPartsJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Completes a direct external upload
    /// </summary>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsCompleteExternalUploadJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Completes an external upload initialized with /get-presigned-put. The
    /// file will be moved from its temporary location in external storage to
    /// a final destination in the S3 bucket. An Upload record will also be
    /// created in the database in most cases.
    /// <para>
    /// If a sha1-checksum was provided in the initial request it will also
    /// be compared with the uploaded file in storage to make sure the same
    /// file was uploaded. The file size will be compared for the same reason.
    /// </para>
    /// <para>
    /// You must have the correct permissions and CORS settings configured in your
    /// external provider. We support AWS S3 as the default. See:
    /// </para>
    /// <para>
    /// https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
    /// </para>
    /// <para>
    /// An external file store must be set up and <c>enable_direct_s3_uploads</c> must
    /// be set to true for this endpoint to function.
    /// </para>
    /// </remarks>
    public Task<UploadsCompleteExternalUploadJsonResponse> CompleteExternalUpload(UploadsCompleteExternalUploadJsonRequest? body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads/complete-external-upload.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<UploadsCompleteExternalUploadJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Complete multipart upload
    /// </summary>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsCompleteMultipartJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Completes the multipart upload in the external store, and copies the
    /// file from its temporary location to its final location in the store.
    /// All of the parts must have been uploaded to the external storage provider.
    /// An Upload record will be completed in most cases once the file is copied
    /// to its final location.
    /// <para>
    /// You must have the correct permissions and CORS settings configured in your
    /// external provider. We support AWS S3 as the default. See:
    /// </para>
    /// <para>
    /// https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
    /// </para>
    /// <para>
    /// An external file store must be set up and <c>enable_direct_s3_uploads</c> must
    /// be set to true for this endpoint to function.
    /// </para>
    /// </remarks>
    public Task<UploadsCompleteMultipartJsonResponse> CompleteMultipart(UploadsCompleteMultipartJsonRequest? body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads/complete-multipart.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<UploadsCompleteMultipartJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Creates a multipart external upload
    /// </summary>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsCreateMultipartJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Creates a multipart upload in the external storage provider, storing
    /// a temporary reference to the external upload similar to /get-presigned-put.
    /// <para>
    /// You must have the correct permissions and CORS settings configured in your
    /// external provider. We support AWS S3 as the default. See:
    /// </para>
    /// <para>
    /// https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
    /// </para>
    /// <para>
    /// An external file store must be set up and <c>enable_direct_s3_uploads</c> must
    /// be set to true for this endpoint to function.
    /// </para>
    /// </remarks>
    public Task<UploadsCreateMultipartJsonResponse> CreateMultipartUpload(UploadsCreateMultipartJsonRequest? body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads/create-multipart.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<UploadsCreateMultipartJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Creates an upload
    /// </summary>
    /// <param name="uploadType"></param>
    /// <param name="userId"></param>
    /// <param name="synchronous"></param>
    /// <param name="file"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    public Task<UploadsJsonResponse> CreateUpload(UploadType uploadType,
        int? userId,
        bool? synchronous,
        BinaryContent? file,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            FormRequest.Create([new MultipartParam("upload_type", uploadType),
                    new MultipartParam("user_id", userId),
                    new MultipartParam("synchronous", synchronous),
                    new MultipartParam("file", file)]),
            JsonResponse.Create<UploadsJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Initiates a direct external upload
    /// </summary>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="UploadsGeneratePresignedPutJsonResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Direct external uploads bypass the usual method of creating uploads
    /// via the POST /uploads route, and upload directly to an external provider,
    /// which by default is S3. This route begins the process, and will return
    /// a unique identifier for the external upload as well as a presigned URL
    /// which is where the file binary blob should be uploaded to.
    /// <para>
    /// Once the upload is complete to the external service, you must call the
    /// POST /complete-external-upload route using the unique identifier returned
    /// by this route, which will create any required Upload record in the Discourse
    /// database and also move file from its temporary location to the final
    /// destination in the external storage service.
    /// </para>
    /// <para>
    /// You must have the correct permissions and CORS settings configured in your
    /// external provider. We support AWS S3 as the default. See:
    /// </para>
    /// <para>
    /// https://meta.discourse.org/t/-/210469#s3-multipart-direct-uploads-4.
    /// </para>
    /// <para>
    /// An external file store must be set up and <c>enable_direct_s3_uploads</c> must
    /// be set to true for this endpoint to function.
    /// </para>
    /// </remarks>
    public Task<UploadsGeneratePresignedPutJsonResponse> GeneratePresignedPut(UploadsGeneratePresignedPutJsonRequest? body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/uploads/generate-presigned-put.json"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<UploadsGeneratePresignedPutJsonResponse>(),
            RawErrorResponse.Instance,
            [],
            requestOptions,
            ct);
}
